post:
  operationId: PostTranslationsSettingsBatch
  summary: Manage Translation Settings
  description: Create, update, or delete multiple translation settings.
  x-authenticated: true
  security:
    - api_token: []
    - cookie_auth: []
    - jwt_token: []
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/AdminBatchTranslationSettings.yaml
  x-codeSamples:
    - lang: JavaScript
      label: JS SDK
      source:
        $ref: ../code_samples/JavaScript/admin_translations_settings_batch/post.js
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/admin_translations_settings_batch/post.sh
  tags:
    - Translations
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AdminBatchTranslationSettingsResponse.yaml
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
  x-workflow: batchTranslationSettingsWorkflow
  x-events: []
  x-since: 2.13.0
  x-featureFlag: translation
