type: object
description: The translation settings to create.
x-schemaName: AdminCreateTranslationSettings
required:
  - entity_type
  - fields
properties:
  entity_type:
    type: string
    title: entity_type
    description: The entity type to create the translation settings for.
    example: product
  fields:
    type: array
    description: The fields to support translations for.
    items:
      type: string
      title: fields
      description: A field to support translations for.
      example: title
  is_active:
    type: boolean
    title: is_active
    description: Whether translations are active for the given entity type.
