type: object
description: The translation settings' details.
x-schemaName: AdminTranslationSettingsResponse
required:
  - translation_settings
properties:
  translation_settings:
    type: object
    description: The translation settings details.
